export const surveyQuestions = [
  {
    "id": "Q1",
    "text": "Q1. Which of the following best describes your role in this community? (Select one)",
    "options": [
      "Village Resident",
      "Farmer",
      "Agricultural Labourer",
      "Fisherman/Fisherwoman",
      "Student",
      "Parent/Guardian",
      "Teacher",
      "Government Employee",
      "Panchayat Member",
      "Ward Councillor",
      "Self Help Group (SHG) Member",
      "Small Business Owner",
      "Shopkeeper",
      "Industrial Worker",
      "Healthcare Worker",
      "NGO/Volunteer Organization Member",
      "Senior Citizen",
      "Homemaker",
      "Person with Disability",
      "Other (Please specify): ______________________"
    ],
    "type": "radio",
    "limit": 1
  },
  {
    "id": "Q2",
    "text": "Q2. How long have you been living or working in this community? (Select one)",
    "options": [
      "Less than 1 year",
      "1–3 years",
      "4–7 years",
      "8–10 years",
      "11–15 years",
      "More than 15 years",
      "Since birth"
    ],
    "type": "radio",
    "limit": 1
  },
  {
    "id": "Q3",
    "text": "Q3. Which statement best describes your overall experience of living or working in this community? (Select one)",
    "options": [
      "Very satisfied because the community provides most of the facilities required for a good quality of life.",
      "Satisfied, but there are a few issues that need improvement.",
      "Neutral, as the community has both strengths and challenges.",
      "Dissatisfied because several important facilities and services are inadequate.",
      "Very dissatisfied due to serious social, environmental, or infrastructure-related problems.",
      "Unable to comment."
    ],
    "type": "radio",
    "limit": 1
  },
  {
    "id": "Q4",
    "text": "Q4. Which of the following community facilities do you or your family regularly use? (Select up to five)",
    "options": [
      "Government School",
      "Private School",
      "Anganwadi Centre",
      "Primary Health Centre",
      "Government Hospital",
      "Private Clinic",
      "Panchayat Office",
      "Community Hall",
      "Public Library",
      "Public Distribution System (Ration Shop)",
      "Bank",
      "ATM",
      "Post Office",
      "Bus Stop/Bus Stand",
      "Public Drinking Water Facility",
      "Public Toilet",
      "Weekly Market",
      "Park/Playground",
      "Internet/Common Service Centre",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q5",
    "text": "Q5. In your opinion, what are the five most important strengths or positive aspects of your community? (Select up to five)",
    "options": [
      "Strong community cooperation",
      "Safe and peaceful environment",
      "Good drinking water availability",
      "Good agricultural resources",
      "Fertile land",
      "Good educational institutions",
      "Good healthcare facilities",
      "Good road connectivity",
      "Reliable electricity supply",
      "Strong women's self-help groups",
      "Active youth participation",
      "Rich cultural heritage",
      "Religious harmony",
      "Clean surroundings",
      "Green environment",
      "Employment opportunities",
      "Digital connectivity",
      "Supportive local administration",
      "Tourism potential",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q6",
    "text": "Q6. Which of the following problems are currently affecting your community? (Select up to five)",
    "options": [
      "Shortage of safe drinking water",
      "Poor quality of drinking water",
      "Inadequate sanitation facilities",
      "Poor drainage system",
      "Flooding or waterlogging",
      "Improper solid waste management",
      "Plastic waste pollution",
      "Air pollution",
      "Noise pollution",
      "Poor road conditions",
      "Lack of street lighting",
      "Frequent electricity interruptions",
      "Poor internet/mobile connectivity",
      "Inadequate healthcare services",
      "Poor educational facilities",
      "Youth unemployment",
      "Lack of skill development opportunities",
      "Women's safety concerns",
      "Alcohol or substance abuse",
      "Agricultural challenges",
      "Climate-related issues (heat, drought, floods)",
      "Lack of public transport",
      "Poor public services",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q7",
    "text": "Q7. Among the problems you selected above, which one has the greatest impact on your family's daily life? (Select one)",
    "options": [
      "Drinking water",
      "Sanitation",
      "Waste management",
      "Drainage",
      "Electricity",
      "Roads and transportation",
      "Healthcare",
      "Education",
      "Employment",
      "Agriculture",
      "Women's safety",
      "Digital connectivity",
      "Environmental pollution",
      "Climate-related events",
      "Other (Specify): ______________________"
    ],
    "type": "radio",
    "limit": 1
  },
  {
    "id": "Q8",
    "text": "Q8. How frequently does the problem selected above affect your family or community? (Select one)",
    "options": [
      "Every day",
      "Several times a week",
      "Once a week",
      "A few times each month",
      "During specific seasons (summer, monsoon, etc.)",
      "Only during emergencies",
      "Rarely"
    ],
    "type": "radio",
    "limit": 1
  },
  {
    "id": "Q9",
    "text": "Q9. Who is most affected by the major problems in your community? (Select up to three)",
    "options": [
      "Children",
      "School Students",
      "College Students",
      "Women",
      "Pregnant Women",
      "Senior Citizens",
      "Persons with Disabilities",
      "Farmers",
      "Agricultural Labourers",
      "Small Business Owners",
      "Daily Wage Workers",
      "Unemployed Youth",
      "Entire Community",
      "Visitors",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 3
  },
  {
    "id": "Q10",
    "text": "Q10. What are the major impacts of these community problems? (Select up to five)",
    "options": [
      "Increased health problems",
      "Higher medical expenses",
      "Reduced quality of drinking water",
      "School absenteeism",
      "Loss of employment opportunities",
      "Reduced family income",
      "Lower agricultural productivity",
      "Increased environmental pollution",
      "Time lost in accessing basic services",
      "Reduced safety and security",
      "Increased stress and mental health concerns",
      "Migration to other places",
      "Poor quality of life",
      "Reduced participation in community activities",
      "Increased conflicts within the community",
      "Loss of biodiversity or natural resources",
      "Reduced opportunities for women and youth",
      "Increased vulnerability during disasters",
      "Difficulty accessing government services",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q11",
    "text": "Q11. Which of the following best describes your household's primary source of drinking water throughout the year? (Select one)",
    "options": [
      "Individual household tap connection",
      "Shared tap connection",
      "Public tap",
      "Borewell",
      "Open well",
      "Protected well",
      "Hand pump",
      "Water tanker",
      "RO water plant",
      "Packaged drinking water",
      "River",
      "Pond",
      "Canal",
      "Rainwater storage",
      "Seasonal water source",
      "Other (Specify): ______________________"
    ],
    "type": "radio",
    "limit": 1
  },
  {
    "id": "Q12",
    "text": "Q12. What are the main reasons for drinking water-related difficulties in your community? (Select up to five)",
    "options": [
      "Insufficient water supply",
      "Water available only during certain hours",
      "Seasonal water shortage",
      "Poor water quality",
      "Water contamination",
      "Salinity",
      "Fluoride or iron content",
      "Leakage in pipelines",
      "Lack of water storage facilities",
      "Long distance to collect water",
      "Frequent breakdown of water supply system",
      "Poor maintenance of water infrastructure",
      "High cost of water",
      "Over-extraction of groundwater",
      "Climate change and reduced rainfall",
      "Population growth",
      "Lack of rainwater harvesting",
      "No major issues",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q13",
    "text": "Q13. Which sanitation-related issues are commonly observed in your locality? (Select up to five)",
    "options": [
      "Open drainage",
      "Blocked drains",
      "Overflowing sewage",
      "Lack of household toilets",
      "Lack of public toilets",
      "Poor maintenance of public toilets",
      "Wastewater stagnation",
      "Mosquito breeding",
      "Foul smell",
      "Waterlogging during rainy season",
      "Poor septic tank maintenance",
      "Illegal sewage discharge",
      "No major sanitation issues",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q14",
    "text": "Q14. How do households in your locality usually dispose of solid waste? (Select all that apply)",
    "options": [
      "Door-to-door waste collection",
      "Community waste bins",
      "Waste segregation at source",
      "Composting of biodegradable waste",
      "Recycling through scrap collectors",
      "Burning of waste",
      "Open dumping in vacant land",
      "Disposal into drains",
      "Disposal into lakes, ponds or rivers",
      "Private waste collection service",
      "Waste buried in the ground",
      "No organized waste collection system",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 99
  },
  {
    "id": "Q15",
    "text": "Q15. Which environmental issues have become more serious in your community during the last five years? (Select up to five)",
    "options": [
      "Increase in plastic waste",
      "Water pollution",
      "Air pollution",
      "Noise pollution",
      "Reduction in groundwater level",
      "Tree cutting",
      "Loss of biodiversity",
      "Soil erosion",
      "Illegal dumping of waste",
      "Increase in mosquitoes and pests",
      "Flooding",
      "Drought",
      "Heat waves",
      "Encroachment of water bodies",
      "No significant environmental changes",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q16",
    "text": "Q16. Which natural resources in your community require immediate conservation and protection? (Select up to five)",
    "options": [
      "Groundwater",
      "Lakes",
      "Ponds",
      "Rivers",
      "Streams",
      "Agricultural land",
      "Forest areas",
      "Trees",
      "Grazing land",
      "Wetlands",
      "Coastal ecosystem (if applicable)",
      "Local biodiversity",
      "Traditional water bodies",
      "Medicinal plants",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q17",
    "text": "Q17. Which environmental improvement initiatives would you actively support if implemented in your community? (Select up to five)",
    "options": [
      "Rainwater harvesting",
      "Tree plantation",
      "Household composting",
      "Plastic-free community campaign",
      "Waste segregation at source",
      "Recycling programme",
      "Lake or pond restoration",
      "Community cleanliness drive",
      "Kitchen garden promotion",
      "Water conservation awareness",
      "Biodiversity conservation",
      "Community nursery",
      "Green public spaces",
      "Solar-powered public facilities",
      "Climate change awareness programmes",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q18",
    "text": "Q18. Which public infrastructure requires the highest priority for improvement to enhance the quality of life in your community? (Select up to five)",
    "options": [
      "Internal roads",
      "Main roads",
      "Footpaths",
      "Drainage system",
      "Drinking water distribution network",
      "Public toilets",
      "Street lighting",
      "Bus shelter",
      "Public transport facilities",
      "Health centre",
      "Government school",
      "Anganwadi centre",
      "Community hall",
      "Public parks",
      "Sports facilities",
      "Waste collection points",
      "Digital service centre",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q19",
    "text": "Q19. How prepared do you think your community is to respond to natural disasters such as floods, cyclones, droughts, heat waves, or other emergencies? (Select one)",
    "options": [
      "Very well prepared with emergency plans and trained volunteers",
      "Moderately prepared with some resources available",
      "Limited preparedness with inadequate facilities",
      "Not prepared and requires significant improvement",
      "Not aware of any disaster preparedness measures",
      "Unable to comment"
    ],
    "type": "radio",
    "limit": 1
  },
  {
    "id": "Q20",
    "text": "Q20. If SRM TRP Engineering College implements one environmental or infrastructure development project in your community, which project would you recommend as the highest priority? (Select up to five)",
    "options": [
      "Smart drinking water quality monitoring system",
      "Rainwater harvesting structures",
      "Greywater treatment and reuse",
      "Household waste segregation programme",
      "Plastic-free community initiative",
      "Compost production unit",
      "Smart drainage monitoring system",
      "Lake, pond or canal restoration",
      "Solar street lighting",
      "Community weather monitoring station",
      "Flood early warning system",
      "Tree plantation and biodiversity park",
      "GIS-based community infrastructure mapping",
      "Green public spaces and urban gardening",
      "Water conservation awareness programme",
      "Climate resilience planning",
      "Community environmental monitoring mobile app",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q21",
    "text": "Q21. Which health-related challenges have the greatest impact on the well-being of people in your community? (Select up to five)",
    "options": [
      "Limited access to primary healthcare services",
      "Lack of specialist medical care",
      "High cost of medical treatment",
      "Lack of affordable medicines",
      "Malnutrition among children",
      "Anaemia among women and adolescents",
      "Diabetes",
      "High blood pressure",
      "Heart-related diseases",
      "Respiratory illnesses",
      "Water-borne diseases",
      "Mosquito-borne diseases",
      "Mental health issues",
      "Alcohol or substance abuse",
      "Poor maternal healthcare",
      "Poor child healthcare",
      "Lack of preventive health awareness",
      "Lack of emergency medical services",
      "No major health-related challenges",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q22",
    "text": "Q22. Which preventive healthcare and wellness initiatives would benefit your community the most? (Select up to five)",
    "options": [
      "General health screening camps",
      "Eye screening camps",
      "Dental health camps",
      "Diabetes screening programmes",
      "Blood pressure monitoring camps",
      "Women's health awareness programmes",
      "Maternal and child healthcare programmes",
      "Nutrition and healthy diet awareness",
      "Mental health counselling",
      "Yoga and physical fitness programmes",
      "First-aid and emergency response training",
      "Vaccination awareness campaigns",
      "Water quality testing awareness",
      "Sanitation and hygiene education",
      "Telemedicine services",
      "Elderly healthcare programmes",
      "School health programmes",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q23",
    "text": "Q23. Which educational challenges most affect children and young people in your community? (Select up to five)",
    "options": [
      "School dropout",
      "Poor school infrastructure",
      "Lack of qualified teachers",
      "Lack of science laboratories",
      "Limited computer facilities",
      "Poor internet connectivity",
      "Financial difficulties in continuing education",
      "Lack of career guidance",
      "Lack of higher education opportunities nearby",
      "Poor English communication skills",
      "Low digital literacy",
      "Long travel distance to educational institutions",
      "Lack of educational support for children with disabilities",
      "Low parental involvement in education",
      "No major educational challenges",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q24",
    "text": "Q24. Which educational or skill development programmes should be introduced to improve future opportunities for youth in your community? (Select up to five)",
    "options": [
      "Digital literacy training",
      "Computer programming and coding",
      "Artificial Intelligence and emerging technologies",
      "Robotics and STEM education",
      "Spoken English and communication skills",
      "Career counselling and higher education guidance",
      "Entrepreneurship development",
      "Financial literacy",
      "Competitive examination coaching",
      "Vocational and technical skill training",
      "Agricultural technology training",
      "Green jobs and sustainability training",
      "Leadership and personality development",
      "Women's skill development programmes",
      "Life skills and problem-solving workshops",
      "Innovation and design thinking workshops",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q25",
    "text": "Q25. Which livelihood and employment challenges are most common in your community? (Select up to five)",
    "options": [
      "Lack of local employment opportunities",
      "Seasonal employment",
      "Low household income",
      "Youth unemployment",
      "Women's unemployment",
      "Lack of vocational skills",
      "Limited entrepreneurship opportunities",
      "Poor market access for local products",
      "High agricultural production costs",
      "Crop losses due to climate change",
      "Lack of access to financial support",
      "Migration in search of employment",
      "Limited industrial development",
      "Lack of business mentoring",
      "No significant livelihood challenges",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q26",
    "text": "Q26. Which initiatives would most effectively improve livelihoods and economic opportunities in your community? (Select up to five)",
    "options": [
      "Skill development centre",
      "Women's entrepreneurship training",
      "Farmer Producer Organisation (FPO) support",
      "Organic farming promotion",
      "Food processing and value addition training",
      "Dairy development initiatives",
      "Poultry farming support",
      "Fisheries development",
      "Digital marketing training",
      "E-commerce and online business support",
      "Start-up incubation and mentoring",
      "Self-Help Group strengthening",
      "Microfinance and financial inclusion",
      "Employment information and placement centre",
      "Community business incubation hub",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q27",
    "text": "Q27. Which groups in your community require additional support to ensure inclusive development? (Select up to five)",
    "options": [
      "Children",
      "Adolescents",
      "Women",
      "Senior citizens",
      "Persons with disabilities",
      "Farmers",
      "Agricultural labourers",
      "Unemployed youth",
      "Single women",
      "Widows",
      "Tribal communities (where applicable)",
      "Migrant workers",
      "Small business owners",
      "Self-Help Groups",
      "Economically weaker families",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q28",
    "text": "Q28. Which social awareness programmes should be organised regularly to improve the quality of life in your community? (Select up to five)",
    "options": [
      "Health and hygiene awareness",
      "Nutrition awareness",
      "Water conservation awareness",
      "Waste segregation and recycling awareness",
      "Climate change awareness",
      "Disaster preparedness training",
      "Women's rights and empowerment",
      "Child protection awareness",
      "Cyber safety and digital security",
      "Financial literacy",
      "Government welfare schemes awareness",
      "Road safety awareness",
      "Drug and alcohol prevention programmes",
      "Environmental conservation awareness",
      "Entrepreneurship awareness",
      "Legal awareness programmes",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q29",
    "text": "Q29. Which factors prevent people in your community from actively participating in development programmes? (Select up to five)",
    "options": [
      "Lack of awareness",
      "Lack of time",
      "Financial constraints",
      "Lack of trust in programmes",
      "Poor communication",
      "Limited leadership",
      "Lack of motivation",
      "Transportation difficulties",
      "Gender-related barriers",
      "Cultural or social barriers",
      "Previous unsuccessful experiences",
      "Lack of support from local institutions",
      "Limited opportunities to participate",
      "No major barriers",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q30",
    "text": "Q30. If SRM TRP Engineering College could implement one project to improve health, education, livelihood, or social development in your community, which project would you recommend as the highest priority? (Select up to five)",
    "options": [
      "Community digital learning centre",
      "STEM laboratory for school students",
      "Mobile health screening programme",
      "Telemedicine support centre",
      "Women's entrepreneurship and business development centre",
      "Youth skill development and employment centre",
      "Farmer innovation and advisory centre",
      "Digital literacy training programme",
      "Career guidance and higher education counselling",
      "Community nutrition improvement programme",
      "Smart health monitoring system",
      "Financial literacy and entrepreneurship programme",
      "Community innovation and design thinking hub",
      "Accessible learning and support services for persons with disabilities",
      "Community resource and knowledge centre",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q31",
    "text": "Q31. Which public services require the greatest improvement to enhance the quality of life in your community? (Select up to five)",
    "options": [
      "Drinking water supply services",
      "Solid waste collection and management",
      "Drainage and sewage maintenance",
      "Electricity supply",
      "Street lighting maintenance",
      "Public healthcare services",
      "Government school services",
      "Public transportation",
      "Road maintenance",
      "Agricultural extension services",
      "Veterinary healthcare services",
      "Public distribution system (ration services)",
      "Banking and financial inclusion services",
      "Digital government services",
      "Emergency response services",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q32",
    "text": "Q32. Which challenges prevent government or community development programmes from achieving better outcomes in your locality? (Select up to five)",
    "options": [
      "Lack of community participation",
      "Insufficient funding",
      "Poor planning",
      "Delayed implementation",
      "Lack of technical expertise",
      "Poor maintenance after project completion",
      "Limited awareness among residents",
      "Weak coordination between departments",
      "Lack of transparency",
      "Lack of monitoring and evaluation",
      "Shortage of trained volunteers",
      "Political interference",
      "Climate-related disruptions",
      "No major implementation challenges",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q33",
    "text": "Q33. Which digital services would be most useful for improving daily life in your community? (Select up to five)",
    "options": [
      "Online access to government services",
      "Digital payment assistance",
      "Community information portal",
      "Online education services",
      "Telemedicine and online healthcare",
      "Employment information portal",
      "Farmer advisory and weather information",
      "Disaster early warning alerts",
      "Water supply updates",
      "Public grievance tracking system",
      "Community event notifications",
      "Digital library",
      "Village/mobile community application",
      "Free public Wi-Fi",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q34",
    "text": "Q34. Which barriers prevent people in your community from effectively using digital technologies and online services? (Select up to five)",
    "options": [
      "Lack of smartphones",
      "Poor mobile network coverage",
      "Poor internet connectivity",
      "High internet costs",
      "Lack of digital literacy",
      "Language barriers",
      "Fear of cyber fraud",
      "Lack of confidence in using technology",
      "Lack of technical support",
      "Irregular electricity supply",
      "Accessibility issues for persons with disabilities",
      "Lack of awareness of digital services",
      "No significant barriers",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q35",
    "text": "Q35. Which renewable energy and energy conservation initiatives should be promoted in your community? (Select up to five)",
    "options": [
      "Solar street lighting",
      "Rooftop solar power systems",
      "Solar-powered drinking water pumps",
      "Solar water heating systems",
      "Biogas plants",
      "Biomass energy utilisation",
      "Energy-efficient LED awareness programmes",
      "Community solar charging stations",
      "Electric vehicle charging infrastructure",
      "Household energy conservation awareness",
      "Smart electricity monitoring systems",
      "Wind energy demonstration projects (where feasible)",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q36",
    "text": "Q36. Which technologies could best help solve the major problems faced by your community? (Select up to five)",
    "options": [
      "Smart water quality monitoring",
      "Smart water level monitoring",
      "GIS-based village mapping",
      "Drone-based agricultural surveys",
      "AI-based crop disease detection",
      "IoT-based irrigation systems",
      "Smart waste collection monitoring",
      "Air quality monitoring systems",
      "Flood monitoring and early warning systems",
      "Telemedicine kiosks",
      "Smart street lighting",
      "Community mobile application",
      "Digital learning centres",
      "Smart energy management systems",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q37",
    "text": "Q37. Which organisations should work together to achieve sustainable development in your community? (Select up to five)",
    "options": [
      "Gram Panchayat",
      "Municipality/Corporation",
      "District Administration",
      "SRM TRP Engineering College",
      "Government Schools",
      "Government Departments",
      "Non-Governmental Organisations (NGOs)",
      "Self Help Groups (SHGs)",
      "Youth Clubs",
      "Farmer Producer Organisations",
      "Private Industries through CSR",
      "Banks and Financial Institutions",
      "Hospitals and Healthcare Institutions",
      "Community-Based Organisations",
      "All of the above",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q38",
    "text": "Q38. If a community mobile application is developed, which features would be most useful to you? (Select up to five)",
    "options": [
      "Report community problems with photographs",
      "Track complaint status",
      "Access government welfare scheme information",
      "Register for health camps and awareness programmes",
      "View water supply schedules",
      "Receive weather and disaster alerts",
      "View waste collection schedules",
      "Access employment opportunities",
      "Register for training programmes",
      "Receive educational announcements",
      "Submit suggestions and feedback",
      "View project progress dashboards",
      "Volunteer registration",
      "Emergency contact directory",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q39",
    "text": "Q39. What factors would encourage you to actively participate in community development projects? (Select up to five)",
    "options": [
      "Clear information about project objectives",
      "Opportunity to participate in decision-making",
      "Visible benefits to the community",
      "Regular communication from organisers",
      "Technical guidance and training",
      "Recognition for volunteers",
      "Transparent use of project funds",
      "Support from local leaders",
      "Flexible participation schedules",
      "Involvement of students and educational institutions",
      "Participation of women and youth",
      "Long-term maintenance plans",
      "Community ownership of projects",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q40",
    "text": "Q40. If SRM TRP Engineering College implements a technology or innovation-based project in your community, which project should receive the highest priority? (Select up to five)",
    "options": [
      "Smart drinking water monitoring system",
      "IoT-based water conservation system",
      "Smart waste segregation and monitoring",
      "GIS-based community infrastructure mapping",
      "Community digital service centre",
      "Telemedicine and digital health platform",
      "Smart agriculture advisory system",
      "Renewable energy demonstration project",
      "Smart street lighting system",
      "Disaster early warning and response system",
      "Digital literacy and technology training centre",
      "Community innovation and maker space",
      "Environmental monitoring dashboard",
      "AI-enabled community decision support system",
      "Integrated Smart Village platform",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q41",
    "text": "Q41. Which factors would motivate you and your family to actively participate in a community development project implemented by SRM TRP Engineering College? (Select up to five)",
    "options": [
      "The project addresses an important community problem",
      "The project provides direct benefits to my family",
      "Opportunity to participate in planning and decision-making",
      "Regular communication about project progress",
      "Transparent use of project resources and funds",
      "Training and capacity-building opportunities",
      "Participation certificates or recognition",
      "Involvement of local leaders and Panchayat",
      "Participation of women and youth",
      "Flexible timing for community activities",
      "Opportunities to volunteer according to my skills",
      "Long-term maintenance and follow-up support",
      "Strong collaboration between the college and the community",
      "Successful implementation of similar projects in nearby areas",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q42",
    "text": "Q42. In what ways would you personally be willing to contribute to the successful implementation of a community project? (Select up to five)",
    "options": [
      "Volunteer my time",
      "Participate in meetings and discussions",
      "Share local knowledge and community history",
      "Help identify community problems",
      "Encourage neighbours to participate",
      "Support awareness campaigns",
      "Help maintain community assets created by the project",
      "Monitor project activities and provide feedback",
      "Share technical or professional expertise",
      "Participate in tree plantation or cleanliness drives",
      "Assist in organising events",
      "Provide space or local resources where possible",
      "I am currently unable to contribute",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q43",
    "text": "Q43. Which methods would you prefer for receiving information and updates about community development projects? (Select up to five)",
    "options": [
      "WhatsApp messages",
      "SMS notifications",
      "Community mobile application",
      "Village notice board",
      "Gram Sabha or community meetings",
      "Panchayat Office",
      "School announcements",
      "Student volunteers",
      "Community volunteers",
      "Local cable television",
      "Community radio",
      "Social media",
      "Email",
      "Printed pamphlets or brochures",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q44",
    "text": "Q44. If a mobile application is developed for your community, which services would you find most useful? (Select up to five)",
    "options": [
      "Report local problems with photographs",
      "Track complaint status",
      "View project progress",
      "Access government welfare schemes",
      "Register for training programmes",
      "Health camp registration",
      "Emergency contact directory",
      "Water supply information",
      "Weather and disaster alerts",
      "Waste collection schedule",
      "Employment opportunities",
      "Agricultural advisory services",
      "Community event calendar",
      "Student volunteer support",
      "Submit suggestions and feedback",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q45",
    "text": "Q45. Which indicators should be used to measure whether a community development project has been successful? (Select up to five)",
    "options": [
      "Improved access to safe drinking water",
      "Better sanitation and hygiene",
      "Cleaner environment",
      "Reduction in disease outbreaks",
      "Increased school attendance",
      "Improved student learning outcomes",
      "Higher employment opportunities",
      "Increased household income",
      "Better agricultural productivity",
      "Greater participation of women",
      "Increased youth engagement",
      "More trees and green spaces",
      "Improved digital access",
      "Better public services",
      "Higher community satisfaction",
      "Strong community ownership of assets",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q46",
    "text": "Q46. How should the community participate in monitoring and evaluating development projects after implementation? (Select up to five)",
    "options": [
      "Monthly community review meetings",
      "Quarterly progress review by the Panchayat",
      "Student and faculty field visits",
      "Community volunteer monitoring",
      "Digital reporting through a mobile application",
      "Public display of project progress",
      "Social audit",
      "Household feedback surveys",
      "Independent technical inspection",
      "Community grievance redressal meetings",
      "Formation of local maintenance committees",
      "Annual impact assessment",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q47",
    "text": "Q47. Which organisations should continue supporting the project after the initial implementation phase? (Select up to five)",
    "options": [
      "Gram Panchayat",
      "Municipality",
      "SRM TRP Engineering College",
      "Local schools",
      "Government departments",
      "Non-Governmental Organisations (NGOs)",
      "Self-Help Groups",
      "Farmer Producer Organisations",
      "Youth clubs",
      "Resident Welfare Associations",
      "Private industries through CSR",
      "Banks and financial institutions",
      "Community volunteers",
      "Healthcare institutions",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q48",
    "text": "Q48. In your opinion, what will ensure that community development projects remain sustainable for many years? (Select up to five)",
    "options": [
      "Strong community ownership",
      "Regular maintenance",
      "Continuous awareness programmes",
      "Technical support from experts",
      "Financial sustainability",
      "Transparent governance",
      "Participation of women and youth",
      "Periodic monitoring and evaluation",
      "Partnerships with educational institutions",
      "Adoption of environmentally friendly technologies",
      "Proper documentation of project outcomes",
      "Capacity building for local leaders",
      "Community contribution towards maintenance",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q49",
    "text": "Q49. Looking ahead to the next five years, which long-term outcomes would you like to see in your community? (Select up to five)",
    "options": [
      "Safe and sufficient drinking water for all",
      "Improved healthcare services",
      "Better educational opportunities",
      "Increased employment and entrepreneurship",
      "Sustainable agriculture",
      "Clean and pollution-free environment",
      "Climate-resilient community",
      "Reliable public infrastructure",
      "Universal digital access",
      "Women-led economic development",
      "Inclusive facilities for persons with disabilities",
      "Strong community participation",
      "Smart and sustainable village/town",
      "Improved quality of life for all",
      "Other (Specify): ______________________"
    ],
    "type": "checkbox",
    "limit": 5
  },
  {
    "id": "Q50",
    "text": "Q50. If SRM TRP Engineering College selects your community for a long-term Community Connect programme, which implementation project should receive the highest priority? (Select one)",
    "options": [
      "Integrated Water Resource Management Project",
      "Smart Water Quality Monitoring System",
      "Sustainable Solid Waste Management Project",
      "Plastic-Free Community Initiative",
      "Renewable Energy and Solar Village Project",
      "Smart Agriculture and Climate Resilience Project",
      "Community Health and Telemedicine Programme",
      "Digital Learning and STEM Education Centre",
      "Women's Entrepreneurship and Livelihood Development Centre",
      "Youth Skill Development and Employment Hub",
      "GIS-Based Village Planning and Infrastructure Mapping",
      "Disaster Risk Reduction and Early Warning System",
      "Biodiversity Conservation and Green Community Programme",
      "Community Innovation and Technology Hub",
      "Inclusive Community Development Project for Vulnerable Groups",
      "Other (Specify): ______________________"
    ],
    "type": "radio",
    "limit": 1
  }
];